### PR TITLE
Standardize aliases, use GetServiceHostName

### LINKED ISSUE #34: Use helper in pkg for domainForServiceName
https://github.com/knative-sandbox/async-component/pull/20#discussion_r512860004

From this discussion, we should be able to use a helper from pkg rather than recreating this function ourselves.

### PR DESCRIPTION
**Pull request by AngeloDanducci**
# Changes

- 🧹 Utilizes GetServiceHostName from pkg, removes local getClusterLocalDomain function

/kind cleanup

Fixes #34

### CODE REVIEW

**Review by beemarie — COMMENTED** [review]
Thanks for these updates -- looks good, will add lgtm label once tests pass.

**Comment by beemarie** [comment]
@AngeloDanducci if you don't have the component running, these changes haven't been tested locally - please do that first.

**Review by maximilien — APPROVED** [review]
LGTM @beemarie are we holding this for a reason?

/approve

**Pull request merged**
