### PR TITLE
adds framework to test other ingresses

### LINKED ISSUE #91: Add integration tests for different ingresses
Add integration tests for the different configurable ingresses

### LINKED ISSUE #103: Use latest prerequisites for E2E tests
As seen [here](https://github.com/knative-sandbox/async-component/blob/main/test/e2e-tests.sh#L45) prerequisites are currently hard coded at 1.0 - but these should be dynamic moving forward.

### PR DESCRIPTION
**Pull request by AngeloDanducci**
# Changes

- supports integration testing for additional ingresses, (kourier, istio, contour, ambassador)

/kind enhancement

Fixes #91 
Fixes #103

### CODE REVIEW

**Comment by AngeloDanducci** [comment]
After reaching out to the community I've changed this so that each networking layer test can run in its own job preventing some of the delete inconsistencies that I was seeing.  This will require a change in [test infra](https://github.com/knative/test-infra/blob/main/config/prod/prow/config_knative.yaml#L522) to specify custom tests for additional networking layers.

By default the E2E test runs using kourier.  After merge I think we should enable istio as well as these have both been successful in my cluster.

Following the discussion in #91 ambassador and contour were not working out of the box.  I think we should use what's working currently and open a new issue to flip the switch (in test infra) to add testing for contour/ambassador when able.

**Review by maximilien — APPROVED** [review]
/ok-to-test
/approve
/lgtm

**Review by maximilien — APPROVED** [review]
/approve
/lgtm

**Pull request merged**
