### PR TITLE
update owners with myself as reviewer

### PR DESCRIPTION
**Pull request by beemarie**

### CODE REVIEW

**Comment by beemarie** [comment]
Looking at the failure:
https://gubernator.knative.dev/build/knative-prow/pr-logs/pull/knative-sandbox_async-component/2/pull-knative-sandbox-async-component-go-coverage/1301968881476177921/

It says: 
```
2020/09/04 19:42:37 Running ProfileReader on bucket 'knative-prow', object='logs/post-knative-sandbox-async-component-go-coverage/1300805590926233600/artifacts/coverage_profile.txt'
2020/09/04 19:42:37 o.NewReader(Ctx) error: storage: object doesn't exist
```

Do we need to create this object somehow since this is a new repo?

**Comment by beemarie** [comment]
> Looking at the failure:
> https://gubernator.knative.dev/build/knative-prow/pr-logs/pull/knative-sandbox_async-component/2/pull-knative-sandbox-async-component-go-coverage/1301968881476177921/
> 
> It says:
> 
> ```
> 2020/09/04 19:42:37 Running ProfileReader on bucket 'knative-prow', object='logs/post-knative-sandbox-async-component-go-coverage/1300805590926233600/artifacts/coverage_profile.txt'
> 2020/09/04 19:42:37 o.NewReader(Ctx) error: storage: object doesn't exist
> ```
> 
> Do we need to create this object somehow since this is a new repo?

@mattmoor any idea about this error? Initially I was thinking it was due to there being no go code, but that doesn't seem to be the case.

**Comment by mattmoor** [comment]
Coverage is non-blocking everywhere IIUC, I think this has to land first.

cc @chizhg

**Pull request merged**
