### PR TITLE
Bumping to latest dependencies v0.21

### PR DESCRIPTION
**Pull request by maximilien**
# Changes

Upgrading to v0.21 using: ./hack/update-deps.sh --upgrade --release v0.21

- :broom: Update dependencies to latest Knative release

/kind cleanup
/assign @julz

### CODE REVIEW

**Review by julz — APPROVED** [review]
let's try out this "approve using only github ui" thing I think we enabled in sandbox recently.

Look ma no "l-g-t-m" :).

**Comment by julz** [comment]
hm, dont think that worked, looks like it's still looking at [OWNERS](https://github.com/knative-sandbox/async-component/blob/master/OWNERS) and Im not in there 😢 

/assign @mattmoor

**Comment by lionelvillard** [comment]
I believe this [PR](https://github.com/knative/test-infra/pull/2674) makes the switch to CODEOWNERS.

Meanwhile:
/lgtm
/approve

**Comment by lionelvillard** [comment]
at least I tried :-)

**Review by mattmoor — APPROVED** [review]
/ok-to-test
/lgtm
/approve

**Pull request merged**
