### PR TITLE
Update hack folder take two

### LINKED ISSUE #16: Update hack folder
Update the hack folder with required files:
- presubmit-tests.sh
- update-deps.sh
- etc.

### PR DESCRIPTION
**Pull request by AngeloDanducci**
Updated dependencies, removed k8s.io pinning.

Duplicate of https://github.com/knative-sandbox/async-component/pull/86 but should have fixed the underlying issues.

# Changes

- :broom: Update dependencies using the update-deps script
- :wastebasket: Remove update-k8s-deps.sh, as well as the replace section of go.mod

/kind cleanup

Fixes #16 

If additional scripts need to be added to the hack folder in the future, they can be updated individually as they may help enable features as we get closer to release ( e2e tests, proper release builds).

Pre submit tests passed, currently verifying everything looks good in my cluster.

### CODE REVIEW

**Review by beemarie — COMMENTED** [review]
Should your .idea/ files be in .gitignore? Not everyone will use the same development environment.

**Comment by AngeloDanducci** [comment]
@beemarie yep absolutely

Curiously this build passes locally but has the same problem as the other PR (which also passed locally).

Looking at the error I wonder if the difference in local vs prow tests is related to this change - [something to do with case (in)sensitivity to openapiv2?](https://github.com/knative-sandbox/async-component/pull/88/files#diff-b318e1e6bbcc59892bb6b4298564b051c6f6d5d848878d14aab856509ff0625cL139)

Going to close this branch and continue troubleshooting in the original.

**Comment by AngeloDanducci** [comment]
@beemarie yep absolutely

Curiously this build passes locally but has the same problem as the other PR (which also passed locally).

Looking at the error I wonder if the difference in local vs prow tests is related to this change - [something to do with case (in)sensitivity to openapiv2?](https://github.com/knative-sandbox/async-component/pull/88/files#diff-b318e1e6bbcc59892bb6b4298564b051c6f6d5d848878d14aab856509ff0625cL139)

Going to close this branch and continue troubleshooting in the original.

**Pull request closed without merging**
