### PR TITLE
Update hack folder

### LINKED ISSUE #16: Update hack folder
Update the hack folder with required files:
- presubmit-tests.sh
- update-deps.sh
- etc.

### PR DESCRIPTION
**Pull request by AngeloDanducci**
updated dependencies, removed k8s.io pinning

# Changes

- :broom: Update dependencies using the update-deps script and go mod vendor
- :wastebasket: Remove update-k8s-deps.sh, as well as the replace section of go.mod

/kind cleanup

Fixes #16 

Spoke with @dprotaso about the updates here, mostly updating and some cleanup removing legacy solutions to guarantee correct k8s.io versions.

If additional scripts need to be added to the hack folder in the future, they can be updated individually as they may help enable features as we get closer to release ( e2e tests, proper release builds).

Pre submit tests passed, currently verifying everything looks good in my cluster.

### CODE REVIEW

**Review by maximilien — COMMENTED** [review]
Did you update after 0.24 since that will be needed as well

**Review by beemarie — COMMENTED** [review]
I don't see the `update-deps` script included. Should it be?

**Comment by AngeloDanducci** [comment]
Is there a new version of `update-deps` that I needed to pull in?  

Also is there a way to run those three test suites locally? Seems I will still need to tweak a few things.

**Comment by dprotaso** [comment]
Looks like it's already in the repo 

https://github.com/knative-sandbox/async-component/blob/main/hack/update-deps.sh


> Also is there a way to run those three test suites locally? Seems I will still need to tweak a few things.

You can run `go test` yourself or you can try
```
./test/presubmit-tests.sh --unit-tests
```

See https://github.com/knative/hack#using-the-presubmit-testssh-helper-script

**Comment by AngeloDanducci** [comment]
Test failures aren't occurring locally but are with prow.  

Issue seems to stem from this:
```
=== Errors
vendor/k8s.io/client-go/discovery/discovery_client.go:30:2: cannot find package "." in:
	/home/prow/go/src/knative.dev/async-component/vendor/github.com/googleapis/gnostic/openapiv2
```

I think that means there's the difference in local vs prow tests is related to this change - [something to do with case (in)sensitivity on mac/linux regarding openapiv2](https://github.com/knative-sandbox/async-component/commit/a8ca2b9fada3ee0b71a6f0c4afa5123d05630850#diff-b318e1e6bbcc59892bb6b4298564b051c6f6d5d848878d14aab856509ff0625cL139) (`github.com/googleapis/gnostic/OpenAPIv2` becoming `github.com/googleapis/gnostic/openapiv2`)

I changed the k8s.io dependencies to match that of knative/serving to no avail - any ideas?

**Comment by dprotaso** [comment]
yeah unfortunately that upstream dependency changed their casing. You can try tweaking your git settings to be aware of case changes. Alternatively I've worked around this by making the changes in two commits.

ie.

1) Delete the problematic dependency and commit that change
2) Run the hack update deps scripts to re-vendor that and commit that as a change

**Review by maximilien — APPROVED** [review]
Did you rebase this?

**Comment by maximilien** [comment]
I see it’s all green :)

/lgtm

**Pull request merged**
